source: alfabeta

engine:
  type: selenium

base_url: https://www.alfabeta.net/companies
schema_version: v1
selectors_version: v1
login:
  enabled: false
  username_env: vishwambhar080@gmail.com
  password_env: iacG@V3hK8LrFUL

rate_limits:
  max_qps: 2
  max_concurrent: 5

proxies:
  max_errors_before_ban: 3
  ban_window_minutes: 30
